services:
  # TODO: frontend; create image for ambrosia-app
  backend:
    image: ambrosia/backend
    build: ./ambrosia-server
    ports:
      - "8080:8080"
    environment:
      - AMBORSIA_BACKEND_PORT=8080
      - POSTGRES_DB=ambrosia
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
    depends_on:
      database:
        condition: service_healthy
        restart: true
  database:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - "./ambrosia-server/database:/var/lib/postgresql/data"
      - "./ambrosia-server/db/sql:/var/lib/ambrosia/db/sql"
    environment:
      - POSTGRES_DB=ambrosia
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
